export enum FrequencyErrorId {
  //Fallback case
  Unknown = "Unknown",
  //Msa Pallet
  KeyAlreadyRegistered = "KeyAlreadyRegistered",
  MsaIdOverflow = "MsaIdOverflow",
  MsaOwnershipInvalidSignature = "MsaOwnershipInvalidSignature",
  NotMsaOwner = "NotMsaOwner",
  MsaInvalidSignature = "MsaInvalidSignature",
  NotKeyOwner = "NotKeyOwner",
  NoKeyExists = "NoKeyExists",
  KeyLimitExceeded = "KeyLimitExceeded",
  InvalidSelfRemoval = "InvalidSelfRemoval",
  InvalidSelfProvider = "InvalidSelfProvider",
  InvalidSchemaId = "InvalidSchemaId",
  DuplicateProvider = "DuplicateProvider",
  AddProviderSignatureVerificationFailed = "AddProviderSignatureVerificationFailed",
  UnauthorizedDelegator = "UnauthorizedDelegator",
  UnauthorizedProvider = "UnauthorizedProvider",
  DelegationRevoked = "DelegationRevoked",
  DelegationNotFound = "DelegationNotFounded",
  DuplicateProviderRegistryEntry = "DuplicateProviderRegistryEntry",
  ExceedsMaxProviderNameSize = "ExceedsMaxProviderNameSize",
  ExceedsMaxSchemaGrantsPerDelegation = "ExceedsMaxSchemaGrantsPerDelegation",
  SchemaNotGranted = "SchemaNotGranted",
  ProviderNotRegistered = "ProviderNotRegistered",
  ProofHasExpired = "ProofHasExpired",
  ProofNotYetValid = "ProofNotYetValid",
  SignatureAlreadySubmitted = "SignatureAlreadySubmitted",
  NewKeyOwnershipInvalidSignature = "NewKeyOwnershipInvalidSignature",
  CannotPredictValidityPastCurrentBlock = "CannotPredictValidityPastCurrentBlock",
  SignatureRegistryLimitExceeded = "SignatureRegistryLimitExceeded",
  SignatureRegistryCorrupted = "SignatureRegistryCorrupted",
  //Balances Pallet
  DeadAccount = "DeadAccount",
  DeltaZero = "DeltaZero",
  ExistentialDeposit = "ExistentialDeposit",
  ExistingVestingSchedule = "ExistingVestingSchedule",
  Expendability = "Expendability",
  InsufficientBalance = "InsufficientBalance",
  IssuanceDeactivated = "IssuanceDeactivated",
  LiquidityRestrictions = "LiquidityRestrictions",
  TooManyFreezes = "TooManyFreezes",
  TooManyHolds = "TooManyHolds",
  TooManyReserves = "TooManyReserves",
  VestingBalance = "VestingBalance",
  //Capacity Pallet
  InvalidTarget = "InvalidTarget",
  InsufficientCapacityBalance = "InsufficientCapacityBalance",
  StakingAmountBelowMinimum = "StakingAmountBelowMinimum",
  ZeroAmountNotAllowed = "ZeroAmountNotAllowed",
  NotAStakingAccount = "NotAStakingAccount",
  NoUnstakedTokensAvailable = "NoUnstakedTokensAvailable",
  UnstakedAmountIsZero = "UnstakedAmountIsZero",
  InsufficientStakingBalance = "InsufficientStakingBalance",
  StakerTargetRelationshipNotFound = "StakerTargetRelationshipNotFound",
  TargetCapacityNotFound = "TargetCapacityNotFound",
  MaxUnlockingChunksExceeded = "MaxUnlockingChunksExceeded",
  IncreaseExceedsAvailable = "IncreaseExceedsAvailable",
  MaxEpochLengthExceeded = "MaxEpochLengthExceeded",
  BalanceTooLowToStake = "BalanceTooLowToStake",
  NoThawedTokenAvailable = "NoThawedTokenAvailable",
  CannotChangeStakingType = "CannotChangeStakingType",
  EraOutOfRange = "EraOutOfRange",
  CannotRetargetToSameProvider = "CannotRetargetToSameProvider",
  NoRewardsEligibleToClaim = "NoRewardsEligibleToClaim",
  MustFirstClaimRewards = "MustFirstClaimRewards",
  MaxRetargetsExceeded = "MaxRetargetsExceeded",
  CollectionBoundExceeded = "CollectionBoundExceeded",
  NotAProviderBoostAccount = "NotAProviderBoostAccount",
  //Passkey Pallet
  PasskeyInvalidSignature = "InvalidSignature",
}

export const substrateErrorToFrequencyErrorId = (section: string, name: string) => {
  return substrateErrorMap[section]?.[name] ?? FrequencyErrorId.Unknown
}

//Values obtained from frequency metadata
//To add values to this, check metadata for indexes, they're not always in alphabetical order
export const substrateErrorMap: {
  [section: string]: { [name: string]: FrequencyErrorId }
} = {
  balances: {
    DeadAccount: FrequencyErrorId.DeadAccount,
    DeltaZero: FrequencyErrorId.DeltaZero,
    ExistentialDeposit: FrequencyErrorId.ExistentialDeposit,
    ExistingVestingSchedule: FrequencyErrorId.ExistingVestingSchedule,
    Expendability: FrequencyErrorId.Expendability,
    InsufficientBalance: FrequencyErrorId.InsufficientBalance,
    IssuanceDeactivated: FrequencyErrorId.IssuanceDeactivated,
    LiquidityRestrictions: FrequencyErrorId.LiquidityRestrictions,
    TooManyFreezes: FrequencyErrorId.TooManyFreezes,
    TooManyHolds: FrequencyErrorId.TooManyHolds,
    TooManyReserves: FrequencyErrorId.TooManyReserves,
    VestingBalance: FrequencyErrorId.VestingBalance,
  },
  capacity: {
    InvalidTarget: FrequencyErrorId.InvalidTarget,
    InsufficientCapacityBalance: FrequencyErrorId.InsufficientCapacityBalance,
    StakingAmountBelowMinimum: FrequencyErrorId.StakingAmountBelowMinimum,
    ZeroAmountNotAllowed: FrequencyErrorId.ZeroAmountNotAllowed,
    NotAStakingAccount: FrequencyErrorId.NotAStakingAccount,
    NoUnstakedTokensAvailable: FrequencyErrorId.NoUnstakedTokensAvailable,
    UnstakedAmountIsZero: FrequencyErrorId.UnstakedAmountIsZero,
    InsufficientStakingBalance: FrequencyErrorId.InsufficientStakingBalance,
    StakerTargetRelationshipNotFound: FrequencyErrorId.StakerTargetRelationshipNotFound,
    TargetCapacityNotFound: FrequencyErrorId.TargetCapacityNotFound,
    MaxUnlockingChunksExceeded: FrequencyErrorId.MaxUnlockingChunksExceeded,
    IncreaseExceedsAvailable: FrequencyErrorId.IncreaseExceedsAvailable,
    MaxEpochLengthExceeded: FrequencyErrorId.MaxEpochLengthExceeded,
    //NOTE(Aziz, 3/12/25): Blockchain error intentionally capitalized improperly (sic), frequency error id fixes typo
    BalanceTooLowtoStake: FrequencyErrorId.BalanceTooLowToStake,
    NoThawedTokenAvailable: FrequencyErrorId.NoThawedTokenAvailable,
    CannotChangeStakingType: FrequencyErrorId.CannotChangeStakingType,
    EraOutOfRange: FrequencyErrorId.EraOutOfRange,
    CannotRetargetToSameProvider: FrequencyErrorId.CannotRetargetToSameProvider,
    NoRewardsEligibleToClaim: FrequencyErrorId.NoRewardsEligibleToClaim,
    MustFirstClaimRewards: FrequencyErrorId.MustFirstClaimRewards,
    MaxRetargetsExceeded: FrequencyErrorId.MaxRetargetsExceeded,
    CollectionBoundExceeded: FrequencyErrorId.CollectionBoundExceeded,
    NotAProviderBoostAccount: FrequencyErrorId.NotAProviderBoostAccount,
  },
  msa: {
    KeyAlreadyRegistered: FrequencyErrorId.KeyAlreadyRegistered,
    MsaIdOverflow: FrequencyErrorId.MsaIdOverflow,
    MsaOwnershipInvalidSignature: FrequencyErrorId.MsaOwnershipInvalidSignature,
    NotMsaOwner: FrequencyErrorId.NotMsaOwner,
    InvalidSignature: FrequencyErrorId.MsaInvalidSignature,
    NotKeyOwner: FrequencyErrorId.NotKeyOwner,
    NoKeyExists: FrequencyErrorId.NoKeyExists,
    KeyLimitExceeded: FrequencyErrorId.KeyLimitExceeded,
    InvalidSelfRemoval: FrequencyErrorId.InvalidSelfRemoval,
    InvalidSelfProvider: FrequencyErrorId.InvalidSelfProvider,
    InvalidSchemaId: FrequencyErrorId.InvalidSchemaId,
    DuplicateProvider: FrequencyErrorId.DuplicateProvider,
    AddProviderSignatureVerificationFailed: FrequencyErrorId.AddProviderSignatureVerificationFailed,
    UnauthorizedDelegator: FrequencyErrorId.UnauthorizedDelegator,
    UnauthorizedProvider: FrequencyErrorId.UnauthorizedProvider,
    DelegationRevoked: FrequencyErrorId.DelegationRevoked,
    DelegationNotFound: FrequencyErrorId.DelegationNotFound,
    DuplicateProviderRegistryEntry: FrequencyErrorId.DuplicateProviderRegistryEntry,
    ExceedsMaxProviderNameSize: FrequencyErrorId.ExceedsMaxProviderNameSize,
    ExceedsMaxSchemaGrantsPerDelegation: FrequencyErrorId.ExceedsMaxSchemaGrantsPerDelegation,
    SchemaNotGranted: FrequencyErrorId.SchemaNotGranted,
    ProviderNotRegistered: FrequencyErrorId.ProviderNotRegistered,
    ProofHasExpired: FrequencyErrorId.ProofHasExpired,
    ProofNotYetValid: FrequencyErrorId.ProofNotYetValid,
    SignatureAlreadySubmitted: FrequencyErrorId.SignatureAlreadySubmitted,
    NewKeyOwnershipInvalidSignature: FrequencyErrorId.NewKeyOwnershipInvalidSignature,
    CannotPredictValidityPastCurrentBlock: FrequencyErrorId.CannotPredictValidityPastCurrentBlock,
    SignatureRegistryLimitExceeded: FrequencyErrorId.SignatureRegistryLimitExceeded,
    SignatureRegistryCorrupted: FrequencyErrorId.SignatureRegistryCorrupted,
  },
  passkey: {
    InvalidSignature: FrequencyErrorId.PasskeyInvalidSignature,
  },
}
