plugins {
  id("io.spring.dependency-management")
  kotlin("jvm")
  kotlin("plugin.spring")
  id("custodial-wallet.jvm-common")
  id("custodial-wallet.jvm-default-quick-test")
}

dependencies {
  compileOnly("org.springframework.boot:spring-boot-configuration-processor")
  implementation(project(":util"))
  implementation(project(":common"))
  implementation(project(":service"))
  implementation("org.slf4j:slf4j-api")
  implementation("org.springframework.boot:spring-boot-starter-webflux")
  implementation("io.projectreactor.kotlin:reactor-kotlin-extensions")
  implementation("org.jetbrains.kotlin:kotlin-reflect")
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
  implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
  implementation("com.google.guava:guava")
  implementation("org.springframework.boot:spring-boot-starter-logging")
  implementation("net.logstash.logback:logstash-logback-encoder")
  implementation("org.springframework.boot:spring-boot-starter")
  implementation("org.json:json")
  implementation("software.amazon.awssdk:ses")
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-jdk8")
  testRuntimeOnly("ch.qos.logback.contrib:logback-jackson")
  testRuntimeOnly("ch.qos.logback.contrib:logback-json-classic")
  testImplementation("org.mockito.kotlin:mockito-kotlin")
  testImplementation("org.springframework.boot:spring-boot-starter-test")
  testImplementation("org.testcontainers:junit-jupiter")
  testImplementation("org.testcontainers:localstack")
  testImplementation("org.springframework.boot:spring-boot-starter-test")
  testImplementation("io.projectreactor:reactor-test")
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}
