CREATE INDEX CONCURRENTLY provider_external_user_detail_user_detail_value_and_user_detail_type ON custodial_wallet.provider_external_user_detail(user_detail_value, user_detail_type);

CREATE INDEX CONCURRENTLY provider_application_provider_frequency_account_id ON custodial_wallet.provider_application(provider_frequency_account_id);
CREATE INDEX CONCURRENTLY user_account_user_identifier_user_account_id ON custodial_wallet.user_account_user_identifier(user_account_id);
