@startuml
start
:Incoming Identifer;
:Choose identifier to verify;
if(isEmail) then(Yes)
    :Send Email;
    :Display Email Sent Page;
    :User Clicks Email Link;
elseif(isSms) then(Yes)
    :Send Sms;
    :Display SMS Form;
    :User Submits SMS Form;
endif
stop
@enduml