spring.web.resources.static-locations=classpath:/static/

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

springdoc.swagger-ui.path=/api

unfinished.show.track.trace.front.end=true
unfinished.enable.stack.trace=true

unfinished.custodial-wallet.aws-sns.region=us-east-2
unfinished.custodial-wallet.aws-sns.service_endpoint=https://sns.us-east-2.amazonaws.com

unfinished.custodial-wallet.aws-ses.region=us-east-2

unfinished.custodial-wallet.aws-kms.region=us-east-2
unfinished.custodial-wallet.aws-kms.service_endpoint=https://kms.us-east-2.amazonaws.com

unfinished.custodial-wallet.ss58.type=42

unfinished.custodial-wallet.db.service.createSchema=true
unfinished.custodial-wallet.db.service.schema=custodial_wallet

spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.max-life-time=300000
spring.r2dbc.pool.max-create-connection-time=1000
spring.r2dbc.pool.max-acquire-time=1000

unfinished.custodial-wallet.redis.expiration=1200s
unfinished.custodial-wallet.signup.expiration=90
unfinished.custodial-wallet.timer.expiration=90s
unfinished.custodial-wallet.signup.resend_limit=5
unfinished.custodial-wallet.signup.resend_freebee=1

unfinished.custodial-wallet.frequency.dynamicValuesReadLockTimeout=1s
unfinished.custodial-wallet.frequency.dynamicValuesWriteLockTimeout=1s
unfinished.custodial-wallet.frequency.cacheSize=100
unfinished.custodial-wallet.frequency.providerNameCache.timeToLive=60s

unfinished.custodial-wallet.ses.cache-timeout=5m

spring.data.redis.connect-timeout=1s
spring.data.redis.timeout=5s

sentry.level.event=ERROR
sentry.level.breadcrumb=INFO

unfinished.lookup.default.max.records=100

unfinished.custodial-wallet.twilio.socket_timeout=10000ms
unfinished.custodial-wallet.twilio.connection_timeout=1000ms
unfinished.custodial-wallet.twilio.maxConnections=50
unfinished.custodial-wallet.twilio.connectionPoolTimeout=1000ms

unfinished.custodial-wallet.handle.reserved_words={'admin', 'everyone', 'all', 'administrator', 'mod', 'moderator', 'here', 'channel'}
unfinished.custodial-wallet.handle.blocked_characters={'"', '#', '%', '(', ')', ',', '.', ':', ';', '<', '>', '@', '\\', '`', '{', '}'}

unfinished.custodial-wallet.incorrect.token.retry.limit=5

unfinished.custodial-wallet.claim-service.maxConnections=200
unfinished.custodial-wallet.claim-service.connectionPoolTimeout=1000ms
unfinished.custodial-wallet.claim-service.connectionTimeout=1000ms
unfinished.custodial-wallet.claim-service.readTimeout=10000ms
unfinished.custodial-wallet.claim-service.writeTimeout=10000ms

unfinished.custodial-wallet.notification-service.maxConnections=200
unfinished.custodial-wallet.notification-service.connectionPoolTimeout=1000ms
unfinished.custodial-wallet.notification-service.connectionTimeout=1000ms
unfinished.custodial-wallet.notification-service.readTimeout=10000ms
unfinished.custodial-wallet.notification-service.writeTimeout=10000ms

unfinished.custodial-wallet.hcaptcha.service_endpoint=https://api.hcaptcha.com
unfinished.custodial-wallet.hcaptcha.status_endpoint=https://www.hcaptchastatus.com
unfinished.custodial-wallet.hcaptcha.include_user_ip=true
unfinished.custodial-wallet.hcaptcha.max_connections=200
unfinished.custodial-wallet.hcaptcha.connection_pool_timeout=1000ms
unfinished.custodial-wallet.hcaptcha.connection_timeout=1000ms
unfinished.custodial-wallet.hcaptcha.read_timeout=10000ms
unfinished.custodial-wallet.hcaptcha.write_timeout=10000ms

unfinished.custodial-wallet.notification.api.rate.limit.count=10000
unfinished.custodial-wallet.notification.api.rate.limit.period=3600s

unfinished.custodial-wallet.provider_metadata.cache.size=32
unfinished.custodial-wallet.provider_metadata.cache.expiration=30s

unfinished.custodial-wallet.localized.messages.cache.size=32

unfinished.custodial-wallet.client.frequency.gateway.account.maxConnections=200
unfinished.custodial-wallet.client.frequency.gateway.account.connectionPoolTimeout=1s
unfinished.custodial-wallet.client.frequency.gateway.account.connectionTimeout=1s
unfinished.custodial-wallet.client.frequency.gateway.account.readTimeout=10s
unfinished.custodial-wallet.client.frequency.gateway.account.writeTimeout=10s

unfinished.custodial-wallet.frequency.developer-terms.copy=By integrating with Frequency Access, you agree to the [Developer Terms of Service]

unfinished.custodial-wallet.migrate-keys.existing-key-pair-type=Sr25519
unfinished.custodial-wallet.migrate-keys.key-usage-type=ACCOUNT
unfinished.custodial-wallet.migrate-keys.missing-key-pair-type=SECP256K1
unfinished.custodial-wallet.migrate-keys.keys-per-batch=3
unfinished.custodial-wallet.migrate-keys.capacity-cost-per-key=1000
unfinished.custodial-wallet.migrate-keys.block-expiration=10

unfinished.custodial-wallet.record.user-activity.expiration=30d
unfinished.custodial-wallet.api.account.change-handle.period=30d
