export enum PasskeyWalletPage {
  SEED_PHRASE = "SEED_PHRASE",
  PHRASE_RECOVERY = "PHRASE_RECOVERY",
  WALLET_CONFIRM = "WALLET_CONFIRM",
  PASSKEY_CREATE = "PASSKEY_CREATE",
  PASSKEY_FINISH = "PASSKEY_FINISH",
}
