@startuml
title "SIWA Login Flow"
actor "User" as u
participant "UserAgent" as ua
participant "Provider" as p
participant "Frequency\nAccess" as fa
database "Postgres" as db
database "Redis" as r
participant "Frequency" as bc
participant "SES" as ses
participant "Notification\nService" as ns

autonumber
u->ua: User would like to login or signup
ua->p: SIWA Button POST
p->fa: POST SignedRequest(publicKey,signature,nonce,callback,permissions)
fa->fa: Validate Signature
fa->bc: retrieve msa by public key
return providerMsaId
fa->fa: check whitelisted providerMsaId
fa->r: Persist Session by sessionId {sessionId,SignedRequest}
return
fa->ua: Render SIWA UserIdentifier Capture Page
ua->fa: Submit Identifier to verify
fa->db: Find UserAccount by userIdentifier
return UserAccount
alt UserAccount Not Found
    note across: See New User Flow
else UserAccount Found
    fa->fa: add UserAccount to Session
    group Identifier Verification
        fa->fa: Generate authenticationCode
        fa->r: Persist Session by authenticationCode and sessionId
        return
        alt isEmail
            fa->ses: Send Email (sessionId and authenticationCode)
            ses->u: Email sent
            u->fa: User Clicks Email
            fa->r: find Session by authenticationCode and sessionId
            return Session
        else isSms
            fa->ns: Send SMS
            fa->ua: Display SMS Form
            ns->u: Sms Message received
            u->ua: Enters authenticationCode
            ua->fa: Submits authenticationCode
            fa->r: find Session by authenticationCode and sessionId
            return Session
        end
    end
end
fa->r: find Session by id
return Session
fa->fa: Add UserKeyData to Session
fa->r: Update Session by id
return
fa->bc: get permissions for userMsaId, providerId
return Permissions for Provider
alt No Permissions for Provider
    note across: Go to Add Permissions
else Is a Login
    alt Permissions disjoint from provider requested permissions
        fa->ua: Render Permissions Screen for all requested permissions for provider and single identifier to send
        ua->fa: Accepts w/Single Identifier
        fa->r: Find Session by id
        return Session
        fa->fa: create and sign addPermissionsPayload chosen key
        fa->fa: Add addPermissionsPayload to Session
    else Pure Login
        fa->ua: Render identifier to send
    end
    fa->fa: Generate authorizationCode
    fa->r: update Session by id, authorizationCode
    return
end
fa->ua: Redirect to callback url with authorizationCode, sessionId
ua->p: Resolve redirect
p->fa: Resolve payload by authorizationCode and sessionId
fa->r: find Session bt authorizationCode and sessionId
return
fa->p: Signed Payload
@enduml