@startuml
start
:Provider sends user who would like to SiWA request(publicKey,callbackUrl,permissions,nonce,optionalUserIdentifiers,signature);
note left
    Lots of conditionals but as far as "screens" are concerned
    these are the unique ones
    1. User Enters in Email or SMS
    2. Display Email Sent Page
    3. Display SMS Form
    4. Display List of Keys with Provider Delegations w/New Key Option
    5. Display Selection of Data to be sent to Provider
    6. Display Permissions Acceptance Screen
    7. Display Permissions Acceptance Screen and Capture Data
       which is really just a permutation of #6

    This is just how I've mapped them for this document,
    not dictating it be this way, merged or split apart up to design
end note
if(Empty optionalUserIdentifiers) then(not migration)
    :User Enters in Email or SMS;
   if(isEmail) then(Yes)
        :Send Email;
        :Display Email Sent Page;
        :User Clicks Email Link;
    elseif(isSms) then(Yes)
        :Send Sms;
        :Display SMS Form;
        :User Submits SMS Form;
    endif
    :Identifier Verified;
    if(Exists in FA?) then(Yes)
        :Display List of Keys with Provider Delegations w/New Key Option;
        note
            There is a lot going on here
            1. Choose the Existing Key to login with
            2. Changing Permissions for this Provider on Existing Key
               May just be passive with #1?
            3. Add this Provider to Existing Key, potential migration
            4. Add this Provider to a New Key, potential migration
            - Migrations aren't really up to the User so those aren't
            "states".
            - Same with changing permissions, I think it's
            just a path for "login" state.
            - New Key is an overt interaction
            - Adding to an existing key is an overt interaction
        end note
        if(useExistingKey) then(Yes)
            note
            Login or Mutate Existing Key
            end note
            if(Has All Permissions For Provider) then(True, Is A Login)
                :Display Selection of Data to be sent to Provider;
                :Redirect to Provider callbackUrl with authorizationCode\n that will resolve the loginPayload;
            else if(Has Some Permissions)
                :Display Permissions Acceptance Screen;
                :Display Selection of Data to be sent to Provider;
                :Redirect to Provider callbackUrl with authorizationCode\n that will resolve the addPermissionsPayload;
            else(False, Add Permissions)
                :Display Permissions Acceptance Screen;
                :Display Selection of Data to be sent to Provider;
                :Redirect to Provider callbackUrl with authorizationCode\n that will resolve the addPermissionsPayload;
            endif
        else(No, New Key)
            :Display Permissions Acceptance Screen and Capture Data;
            :Display Selection of Data to be sent to Provider;
            :Redirect to Provider callbackUrl with authorizationCode\n that will resolve the createSponsoredAccountPayload;
        endif
    else(Doesn't Exist, New User)
        :Display Permissions Acceptance Screen and Capture Data;
        :Display Selection of Data to be sent to Provider;
        :Redirect to Provider callbackUrl with authorizationCode\n that will resolve the createSponsoredAccountPayload;
    endif
else(Migration Case)
    if(Any Exist in FA) then(True, Delta Migration Case)
        :Choose identifier to verify (Needed to avoid "disjoint" security hole);
        if(isEmail) then(Yes)
            :Send Email;
            :Display Email Sent Page;
            :User Clicks Email Link;
        elseif(isSms) then(Yes)
            :Send Sms;
            :Display SMS Form;
            :User Submits SMS Form;
        endif
        :Display Permissions Acceptance Screen and Capture Data;
        :Display Selection of Data to be sent to Provider;
        :Redirect to Provider callbackUrl with authorizationCode\n that will resolve the createSponsoredAccountPayload;
    else(False, New Migration Case)
        :Choose identifier to verify (Needed for Passkey Wallet);
        if(isEmail) then(Yes)
            :Send Email;
            :Display Email Sent Page;
            :User Clicks Email Link;
        elseif(isSms) then(Yes)
            :Send Sms;
            :Display SMS Form;
            :User Submits SMS Form;
        endif
        :Display Permissions Acceptance Screen and Capture Data;
        :Display Selection of Data to be sent to Provider;
        :Redirect to Provider callbackUrl with authorizationCode\n that will resolve the createSponsoredAccountPayload;
    endif
endif
@enduml